spring.application.name=backend
server.port=8080


spring.profiles.include=secret
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

app.jwt.secret=local-dev-only-change-this-secret-key-32b
app.jwt.expiration-ms=3600000



logging.level.root=info
logging.level.com.backend=info