spring.application.name=backend
server.port=8080

logging.level.root=info
logging.level.com.backend=info

spring.profiles.include=secret
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

app.jwt.secret=local-dev-only-change-this-secret-key-32b
app.jwt.expiration-ms=3600000

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

#app.video.max-file-size-bytes=${VIDEO_MAX_FILE_SIZE_BYTES:209715200}
app.video.max-file-size-bytes=${VIDEO_MAX_FILE_SIZE_BYTES:509715200}
app.video.allowed-extensions=${VIDEO_ALLOWED_EXTENSIONS:mov}
app.video.allowed-content-types=${VIDEO_ALLOWED_CONTENT_TYPES:video/quicktime}


app.aws.region=${AWS_REGION:ap-northeast-2}
app.aws.s3.bucket=${AWS_S3_BUCKET:}
app.aws.access-key=${AWS_ACCESS_KEY_ID:}
app.aws.secret-key=${AWS_SECRET_ACCESS_KEY:}

app.ffprobe.path=${FFPROBE_PATH:ffprobe}

